name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  ci:
    name: "Run CI"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.3"
          
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.20'

      - name: Check out code
        uses: actions/checkout@v1

      - name: Run Unit tests and Coverage
        run: go test -v ./... -race -coverprofile=coverage.out -covermode=atomic

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}

  build:
    runs-on: ubuntu-latest
    needs: [ci, test]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...
